"""domain_and_analytics

Revision ID: 93e0ebdb044c
Revises: 0001_identity_security
Create Date: 2026-09-01 20:02:17.827710
"""
from alembic import op
import sqlalchemy as sa


revision = '93e0ebdb044c'
down_revision = '0001_identity_security'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feature_versions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('identifier', sa.String(length=64), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('source_fields_json', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_feature_version_id', 'feature_versions', ['identifier', 'version'], unique=True)
    op.create_table('intelligence_sources',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('external_ref', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('source_type', sa.String(length=64), nullable=False),
    sa.Column('reliability_default', sa.String(length=8), nullable=False),
    sa.Column('confidentiality', sa.String(length=32), nullable=False),
    sa.Column('activity', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.CheckConstraint("reliability_default IN ('A','B','C','D','E','F')", name='ck_intel_source_admiralty_reliability')
    )
    op.create_index(op.f('ix_intelligence_sources_external_ref'), 'intelligence_sources', ['external_ref'], unique=False)
    op.create_index(op.f('ix_intelligence_sources_name'), 'intelligence_sources', ['name'], unique=False)
    op.create_index(op.f('ix_intelligence_sources_source_type'), 'intelligence_sources', ['source_type'], unique=False)
    op.create_table('intelligence_tags',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('color', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_intelligence_tags_name'), 'intelligence_tags', ['name'], unique=True)
    op.create_table('organizations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('external_ref', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('org_type', sa.String(length=64), nullable=True),
    sa.Column('country', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_external_ref'), 'organizations', ['external_ref'], unique=False)
    op.create_index(op.f('ix_organizations_name'), 'organizations', ['name'], unique=False)
    op.create_table('providers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('external_ref', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('provider_type', sa.String(length=64), nullable=True),
    sa.Column('country', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_providers_external_ref'), 'providers', ['external_ref'], unique=False)
    op.create_index(op.f('ix_providers_name'), 'providers', ['name'], unique=False)
    op.create_table('relationship_types',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_relationship_types_name'), 'relationship_types', ['name'], unique=True)
    op.create_table('rule_versions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('rule_id', sa.String(length=64), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('conditions_json', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_rule_version_id', 'rule_versions', ['rule_id', 'version'], unique=True)
    op.create_table('synthetic_scenarios',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('scenario_ref', sa.String(length=64), nullable=False),
    sa.Column('scenario_type', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('subject_type', sa.String(length=32), nullable=True),
    sa.Column('subject_id', sa.Uuid(), nullable=True),
    sa.Column('extra_refs', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_synthetic_scenarios_scenario_ref'), 'synthetic_scenarios', ['scenario_ref'], unique=True)
    op.create_index(op.f('ix_synthetic_scenarios_scenario_type'), 'synthetic_scenarios', ['scenario_type'], unique=False)
    op.create_table('teams',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('external_ref', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('sport', sa.String(length=128), nullable=True),
    sa.Column('federation', sa.String(length=255), nullable=True),
    sa.Column('country', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teams_external_ref'), 'teams', ['external_ref'], unique=False)
    op.create_index(op.f('ix_teams_name'), 'teams', ['name'], unique=False)
    op.create_table('athletes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('external_ref', sa.String(length=64), nullable=False),
    sa.Column('first_name', sa.String(length=128), nullable=False),
    sa.Column('last_name', sa.String(length=128), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('nationality', sa.String(length=64), nullable=True),
    sa.Column('sport', sa.String(length=128), nullable=True),
    sa.Column('discipline', sa.String(length=128), nullable=True),
    sa.Column('team_id', sa.Uuid(), nullable=True),
    sa.Column('gender', sa.String(length=16), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_athletes_external_ref'), 'athletes', ['external_ref'], unique=True)
    op.create_index(op.f('ix_athletes_last_name'), 'athletes', ['last_name'], unique=False)
    op.create_index(op.f('ix_athletes_sport'), 'athletes', ['sport'], unique=False)
    op.create_index(op.f('ix_athletes_status'), 'athletes', ['status'], unique=False)
    op.create_table('entity_relationships',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('from_entity_type', sa.String(length=32), nullable=False),
    sa.Column('from_entity_id', sa.Uuid(), nullable=False),
    sa.Column('relationship_type_id', sa.Uuid(), nullable=False),
    sa.Column('to_entity_type', sa.String(length=32), nullable=False),
    sa.Column('to_entity_id', sa.Uuid(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('source_id', sa.Uuid(), nullable=True),
    sa.Column('metadata', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['relationship_type_id'], ['relationship_types.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_id'], ['intelligence_sources.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entity_relationships_from_entity_type'), 'entity_relationships', ['from_entity_type'], unique=False)
    op.create_index(op.f('ix_entity_relationships_relationship_type_id'), 'entity_relationships', ['relationship_type_id'], unique=False)
    op.create_index(op.f('ix_entity_relationships_to_entity_type'), 'entity_relationships', ['to_entity_type'], unique=False)
    op.create_index('ix_rel_from', 'entity_relationships', ['from_entity_type', 'from_entity_id'], unique=False)
    op.create_index('ix_rel_to', 'entity_relationships', ['to_entity_type', 'to_entity_id'], unique=False)
    op.create_table('supplements',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('external_ref', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('provider_id', sa.Uuid(), nullable=True),
    sa.Column('category', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supplements_external_ref'), 'supplements', ['external_ref'], unique=False)
    op.create_index(op.f('ix_supplements_name'), 'supplements', ['name'], unique=False)
    op.create_table('support_personnel',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('external_ref', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('support_role', sa.String(length=128), nullable=True),
    sa.Column('organization', sa.String(length=255), nullable=True),
    sa.Column('organization_id', sa.Uuid(), nullable=True),
    sa.Column('country', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_support_personnel_external_ref'), 'support_personnel', ['external_ref'], unique=False)
    op.create_index(op.f('ix_support_personnel_name'), 'support_personnel', ['name'], unique=False)
    op.create_table('analysis_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('model_version', sa.String(length=32), nullable=False),
    sa.Column('rule_version', sa.Integer(), nullable=False),
    sa.Column('feature_version', sa.Integer(), nullable=False),
    sa.Column('config_json', sa.JSON(), nullable=False),
    sa.Column('result_count', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_runs_status'), 'analysis_runs', ['status'], unique=False)
    op.create_table('biological_observations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('athlete_id', sa.Uuid(), nullable=False),
    sa.Column('observation_date', sa.Date(), nullable=False),
    sa.Column('marker', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=32), nullable=True),
    sa.Column('baseline_deviation', sa.Float(), nullable=True),
    sa.Column('source_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athletes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['intelligence_sources.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_biological_observations_athlete_id'), 'biological_observations', ['athlete_id'], unique=False)
    op.create_table('intelligence_reports',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('external_ref', sa.String(length=64), nullable=True),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('subject_type', sa.String(length=32), nullable=True),
    sa.Column('subject_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('report_date', sa.Date(), nullable=True),
    sa.Column('ingestion_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('reliability', sa.String(length=8), nullable=True),
    sa.Column('information_quality', sa.String(length=8), nullable=True),
    sa.Column('confidentiality', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('info_category', sa.String(length=64), nullable=True),
    sa.Column('is_duplicate', sa.Boolean(), nullable=False),
    sa.Column('dedupe_key', sa.String(length=255), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['intelligence_sources.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.CheckConstraint("reliability IS NULL OR reliability IN ('A','B','C','D','E','F')", name='ck_intel_report_admiralty_reliability'),
    sa.CheckConstraint("information_quality IS NULL OR information_quality IN ('1','2','3','4','5','6')", name='ck_intel_report_admiralty_quality')
    )
    op.create_index('ix_intel_subject', 'intelligence_reports', ['subject_type', 'subject_id', 'report_date'], unique=False)
    op.create_index(op.f('ix_intelligence_reports_dedupe_key'), 'intelligence_reports', ['dedupe_key'], unique=False)
    op.create_index(op.f('ix_intelligence_reports_external_ref'), 'intelligence_reports', ['external_ref'], unique=False)
    op.create_index(op.f('ix_intelligence_reports_ingestion_date'), 'intelligence_reports', ['ingestion_date'], unique=False)
    op.create_index(op.f('ix_intelligence_reports_report_date'), 'intelligence_reports', ['report_date'], unique=False)
    op.create_index(op.f('ix_intelligence_reports_source_id'), 'intelligence_reports', ['source_id'], unique=False)
    op.create_index(op.f('ix_intelligence_reports_status'), 'intelligence_reports', ['status'], unique=False)
    op.create_index(op.f('ix_intelligence_reports_subject_id'), 'intelligence_reports', ['subject_id'], unique=False)
    op.create_index(op.f('ix_intelligence_reports_subject_type'), 'intelligence_reports', ['subject_type'], unique=False)
    op.create_table('medical_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('athlete_id', sa.Uuid(), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=True),
    sa.Column('event_type', sa.String(length=64), nullable=True),
    sa.Column('provider_id', sa.Uuid(), nullable=True),
    sa.Column('metadata_classification', sa.String(length=64), nullable=True),
    sa.Column('source_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athletes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['intelligence_sources.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_medical_athlete_date', 'medical_events', ['athlete_id', 'event_date'], unique=False)
    op.create_index(op.f('ix_medical_events_athlete_id'), 'medical_events', ['athlete_id'], unique=False)
    op.create_table('supplement_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('athlete_id', sa.Uuid(), nullable=False),
    sa.Column('supplement_id', sa.Uuid(), nullable=True),
    sa.Column('event_date', sa.Date(), nullable=True),
    sa.Column('usage_note', sa.Text(), nullable=True),
    sa.Column('source_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athletes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['intelligence_sources.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['supplement_id'], ['supplements.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supplement_events_athlete_id'), 'supplement_events', ['athlete_id'], unique=False)
    op.create_table('support_person_athletes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('support_person_id', sa.Uuid(), nullable=False),
    sa.Column('athlete_id', sa.Uuid(), nullable=False),
    sa.Column('relationship_type', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athletes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['support_person_id'], ['support_personnel.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_support_person_athletes_athlete_id'), 'support_person_athletes', ['athlete_id'], unique=False)
    op.create_index(op.f('ix_support_person_athletes_support_person_id'), 'support_person_athletes', ['support_person_id'], unique=False)
    op.create_table('testing_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('athlete_id', sa.Uuid(), nullable=False),
    sa.Column('test_date', sa.Date(), nullable=False),
    sa.Column('test_type', sa.String(length=64), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('result_classification', sa.String(length=64), nullable=True),
    sa.Column('laboratory_ref', sa.String(length=128), nullable=True),
    sa.Column('source_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athletes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['intelligence_sources.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_test_athlete_date', 'testing_events', ['athlete_id', 'test_date'], unique=False)
    op.create_index(op.f('ix_testing_events_athlete_id'), 'testing_events', ['athlete_id'], unique=False)
    op.create_table('travel_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('athlete_id', sa.Uuid(), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('origin', sa.String(length=128), nullable=True),
    sa.Column('destination', sa.String(length=128), nullable=True),
    sa.Column('event_type', sa.String(length=64), nullable=True),
    sa.Column('source_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athletes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['intelligence_sources.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_travel_athlete_date', 'travel_events', ['athlete_id', 'event_date'], unique=False)
    op.create_index(op.f('ix_travel_events_athlete_id'), 'travel_events', ['athlete_id'], unique=False)
    op.create_table('whereabouts_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('athlete_id', sa.Uuid(), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=True),
    sa.Column('expected_location', sa.String(length=255), nullable=True),
    sa.Column('observed_location', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('source_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athletes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['intelligence_sources.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_where_athlete_date', 'whereabouts_events', ['athlete_id', 'event_date'], unique=False)
    op.create_index(op.f('ix_whereabouts_events_athlete_id'), 'whereabouts_events', ['athlete_id'], unique=False)
    op.create_table('anomaly_results',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('analysis_run_id', sa.Uuid(), nullable=False),
    sa.Column('subject_type', sa.String(length=32), nullable=False),
    sa.Column('subject_id', sa.Uuid(), nullable=False),
    sa.Column('raw_score', sa.Float(), nullable=False),
    sa.Column('normalized_score', sa.Float(), nullable=False),
    sa.Column('is_anomaly', sa.Boolean(), nullable=False),
    sa.Column('contribution_json', sa.JSON(), nullable=False),
    sa.Column('model_version', sa.String(length=32), nullable=False),
    sa.Column('feature_version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_anomaly_run_subj', 'anomaly_results', ['analysis_run_id', 'subject_type', 'subject_id'], unique=True)
    op.create_table('correlation_results',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('analysis_run_id', sa.Uuid(), nullable=False),
    sa.Column('correlation_type', sa.String(length=16), nullable=False),
    sa.Column('subject_type', sa.String(length=32), nullable=False),
    sa.Column('subject_id', sa.Uuid(), nullable=False),
    sa.Column('window_days', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('signal_count', sa.Integer(), nullable=False),
    sa.Column('category_count', sa.Integer(), nullable=False),
    sa.Column('signal_ids_json', sa.JSON(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_correlation_run_subj', 'correlation_results', ['analysis_run_id', 'correlation_type', 'subject_type', 'subject_id'], unique=False)
    op.create_table('feature_snapshots',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('analysis_run_id', sa.Uuid(), nullable=False),
    sa.Column('subject_type', sa.String(length=32), nullable=False),
    sa.Column('subject_id', sa.Uuid(), nullable=False),
    sa.Column('feature_id', sa.String(length=64), nullable=False),
    sa.Column('feature_version', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('source_fields_json', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_feature_snap_run_subj', 'feature_snapshots', ['analysis_run_id', 'subject_type', 'subject_id'], unique=False)
    op.create_index(op.f('ix_feature_snapshots_feature_id'), 'feature_snapshots', ['feature_id'], unique=False)
    op.create_table('network_results',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('analysis_run_id', sa.Uuid(), nullable=False),
    sa.Column('subject_type', sa.String(length=32), nullable=False),
    sa.Column('subject_id', sa.Uuid(), nullable=False),
    sa.Column('degree', sa.Integer(), nullable=False),
    sa.Column('weighted_degree', sa.Float(), nullable=False),
    sa.Column('relationship_diversity', sa.Integer(), nullable=False),
    sa.Column('connected_priority_count', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('detail_json', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_network_run_subj', 'network_results', ['analysis_run_id', 'subject_type', 'subject_id'], unique=True)
    op.create_table('priority_scores',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('analysis_run_id', sa.Uuid(), nullable=False),
    sa.Column('subject_type', sa.String(length=32), nullable=False),
    sa.Column('subject_id', sa.Uuid(), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=False),
    sa.Column('priority_level', sa.String(length=16), nullable=False),
    sa.Column('rule_score', sa.Float(), nullable=False),
    sa.Column('anomaly_score', sa.Float(), nullable=False),
    sa.Column('correlation_score', sa.Float(), nullable=False),
    sa.Column('temporal_score', sa.Float(), nullable=False),
    sa.Column('network_score', sa.Float(), nullable=False),
    sa.Column('source_quality_score', sa.Float(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('components_json', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_priority_run_subj', 'priority_scores', ['analysis_run_id', 'subject_type', 'subject_id'], unique=True)
    op.create_index(op.f('ix_priority_scores_priority_level'), 'priority_scores', ['priority_level'], unique=False)
    op.create_table('report_tags',
    sa.Column('report_id', sa.Uuid(), nullable=False),
    sa.Column('tag_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['intelligence_reports.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['intelligence_tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('report_id', 'tag_id')
    )
    op.create_table('rule_results',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('analysis_run_id', sa.Uuid(), nullable=False),
    sa.Column('subject_type', sa.String(length=32), nullable=False),
    sa.Column('subject_id', sa.Uuid(), nullable=False),
    sa.Column('rule_id', sa.String(length=64), nullable=False),
    sa.Column('rule_version', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('triggered', sa.Boolean(), nullable=False),
    sa.Column('detail_json', sa.JSON(), nullable=False),
    sa.Column('expression', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rule_results_rule_id'), 'rule_results', ['rule_id'], unique=False)
    op.create_index('ix_rule_results_run_subj', 'rule_results', ['analysis_run_id', 'subject_type', 'subject_id'], unique=False)
    op.create_table('source_assessments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('report_id', sa.Uuid(), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('reliability', sa.String(length=8), nullable=False),
    sa.Column('information_quality', sa.String(length=8), nullable=False),
    sa.Column('assessment_notes', sa.Text(), nullable=True),
    sa.Column('assessed_by', sa.Uuid(), nullable=True),
    sa.Column('assessed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assessed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['report_id'], ['intelligence_reports.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['intelligence_sources.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.CheckConstraint("reliability IN ('A','B','C','D','E','F')", name='ck_source_assessment_admiralty_reliability'),
    sa.CheckConstraint("information_quality IN ('1','2','3','4','5','6')", name='ck_source_assessment_admiralty_quality')
    )
    op.create_index(op.f('ix_source_assessments_report_id'), 'source_assessments', ['report_id'], unique=False)
    op.create_index(op.f('ix_source_assessments_source_id'), 'source_assessments', ['source_id'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('alert_ref', sa.String(length=32), nullable=False),
    sa.Column('analysis_run_id', sa.Uuid(), nullable=False),
    sa.Column('priority_score_id', sa.Uuid(), nullable=False),
    sa.Column('subject_type', sa.String(length=32), nullable=False),
    sa.Column('subject_id', sa.Uuid(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('priority_level', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['priority_score_id'], ['priority_scores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_alert_ref'), 'alerts', ['alert_ref'], unique=True)
    op.create_index(op.f('ix_alerts_created_at'), 'alerts', ['created_at'], unique=False)
    op.create_index('ix_alerts_status', 'alerts', ['status'], unique=False)
    op.create_index('ix_alerts_subject', 'alerts', ['subject_type', 'subject_id', 'created_at'], unique=False)
    op.create_table('alert_signals',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('alert_id', sa.Uuid(), nullable=False),
    sa.Column('signal_type', sa.String(length=16), nullable=False),
    sa.Column('signal_id', sa.Uuid(), nullable=False),
    sa.Column('contributed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_alert_signal_alert', 'alert_signals', ['alert_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_alert_signal_alert', table_name='alert_signals')
    op.drop_table('alert_signals')
    op.drop_index('ix_alerts_subject', table_name='alerts')
    op.drop_index('ix_alerts_status', table_name='alerts')
    op.drop_index(op.f('ix_alerts_created_at'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_alert_ref'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_source_assessments_source_id'), table_name='source_assessments')
    op.drop_index(op.f('ix_source_assessments_report_id'), table_name='source_assessments')
    op.drop_table('source_assessments')
    op.drop_index('ix_rule_results_run_subj', table_name='rule_results')
    op.drop_index(op.f('ix_rule_results_rule_id'), table_name='rule_results')
    op.drop_table('rule_results')
    op.drop_table('report_tags')
    op.drop_index(op.f('ix_priority_scores_priority_level'), table_name='priority_scores')
    op.drop_index('ix_priority_run_subj', table_name='priority_scores')
    op.drop_table('priority_scores')
    op.drop_index('ix_network_run_subj', table_name='network_results')
    op.drop_table('network_results')
    op.drop_index(op.f('ix_feature_snapshots_feature_id'), table_name='feature_snapshots')
    op.drop_index('ix_feature_snap_run_subj', table_name='feature_snapshots')
    op.drop_table('feature_snapshots')
    op.drop_index('ix_correlation_run_subj', table_name='correlation_results')
    op.drop_table('correlation_results')
    op.drop_index('ix_anomaly_run_subj', table_name='anomaly_results')
    op.drop_table('anomaly_results')
    op.drop_index(op.f('ix_whereabouts_events_athlete_id'), table_name='whereabouts_events')
    op.drop_index('ix_where_athlete_date', table_name='whereabouts_events')
    op.drop_table('whereabouts_events')
    op.drop_index(op.f('ix_travel_events_athlete_id'), table_name='travel_events')
    op.drop_index('ix_travel_athlete_date', table_name='travel_events')
    op.drop_table('travel_events')
    op.drop_index(op.f('ix_testing_events_athlete_id'), table_name='testing_events')
    op.drop_index('ix_test_athlete_date', table_name='testing_events')
    op.drop_table('testing_events')
    op.drop_index(op.f('ix_support_person_athletes_support_person_id'), table_name='support_person_athletes')
    op.drop_index(op.f('ix_support_person_athletes_athlete_id'), table_name='support_person_athletes')
    op.drop_table('support_person_athletes')
    op.drop_index(op.f('ix_supplement_events_athlete_id'), table_name='supplement_events')
    op.drop_table('supplement_events')
    op.drop_index(op.f('ix_medical_events_athlete_id'), table_name='medical_events')
    op.drop_index('ix_medical_athlete_date', table_name='medical_events')
    op.drop_table('medical_events')
    op.drop_index(op.f('ix_intelligence_reports_subject_type'), table_name='intelligence_reports')
    op.drop_index(op.f('ix_intelligence_reports_subject_id'), table_name='intelligence_reports')
    op.drop_index(op.f('ix_intelligence_reports_status'), table_name='intelligence_reports')
    op.drop_index(op.f('ix_intelligence_reports_source_id'), table_name='intelligence_reports')
    op.drop_index(op.f('ix_intelligence_reports_report_date'), table_name='intelligence_reports')
    op.drop_index(op.f('ix_intelligence_reports_ingestion_date'), table_name='intelligence_reports')
    op.drop_index(op.f('ix_intelligence_reports_external_ref'), table_name='intelligence_reports')
    op.drop_index(op.f('ix_intelligence_reports_dedupe_key'), table_name='intelligence_reports')
    op.drop_index('ix_intel_subject', table_name='intelligence_reports')
    op.drop_table('intelligence_reports')
    op.drop_index(op.f('ix_biological_observations_athlete_id'), table_name='biological_observations')
    op.drop_table('biological_observations')
    op.drop_index(op.f('ix_analysis_runs_status'), table_name='analysis_runs')
    op.drop_table('analysis_runs')
    op.drop_index(op.f('ix_support_personnel_name'), table_name='support_personnel')
    op.drop_index(op.f('ix_support_personnel_external_ref'), table_name='support_personnel')
    op.drop_table('support_personnel')
    op.drop_index(op.f('ix_supplements_name'), table_name='supplements')
    op.drop_index(op.f('ix_supplements_external_ref'), table_name='supplements')
    op.drop_table('supplements')
    op.drop_index('ix_rel_to', table_name='entity_relationships')
    op.drop_index('ix_rel_from', table_name='entity_relationships')
    op.drop_index(op.f('ix_entity_relationships_to_entity_type'), table_name='entity_relationships')
    op.drop_index(op.f('ix_entity_relationships_relationship_type_id'), table_name='entity_relationships')
    op.drop_index(op.f('ix_entity_relationships_from_entity_type'), table_name='entity_relationships')
    op.drop_table('entity_relationships')
    op.drop_index(op.f('ix_athletes_status'), table_name='athletes')
    op.drop_index(op.f('ix_athletes_sport'), table_name='athletes')
    op.drop_index(op.f('ix_athletes_last_name'), table_name='athletes')
    op.drop_index(op.f('ix_athletes_external_ref'), table_name='athletes')
    op.drop_table('athletes')
    op.drop_index(op.f('ix_teams_name'), table_name='teams')
    op.drop_index(op.f('ix_teams_external_ref'), table_name='teams')
    op.drop_table('teams')
    op.drop_index(op.f('ix_synthetic_scenarios_scenario_type'), table_name='synthetic_scenarios')
    op.drop_index(op.f('ix_synthetic_scenarios_scenario_ref'), table_name='synthetic_scenarios')
    op.drop_table('synthetic_scenarios')
    op.drop_index('ix_rule_version_id', table_name='rule_versions')
    op.drop_table('rule_versions')
    op.drop_index(op.f('ix_relationship_types_name'), table_name='relationship_types')
    op.drop_table('relationship_types')
    op.drop_index(op.f('ix_providers_name'), table_name='providers')
    op.drop_index(op.f('ix_providers_external_ref'), table_name='providers')
    op.drop_table('providers')
    op.drop_index(op.f('ix_organizations_name'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_external_ref'), table_name='organizations')
    op.drop_table('organizations')
    op.drop_index(op.f('ix_intelligence_tags_name'), table_name='intelligence_tags')
    op.drop_table('intelligence_tags')
    op.drop_index(op.f('ix_intelligence_sources_source_type'), table_name='intelligence_sources')
    op.drop_index(op.f('ix_intelligence_sources_name'), table_name='intelligence_sources')
    op.drop_index(op.f('ix_intelligence_sources_external_ref'), table_name='intelligence_sources')
    op.drop_table('intelligence_sources')
    op.drop_index('ix_feature_version_id', table_name='feature_versions')
    op.drop_table('feature_versions')
    # ### end Alembic commands ###
