// Canonical permission keys (mirrored from the backend's 29 permissions).
export const PERMISSIONS = {
  alertsRead: "alerts:read",
  alertsReview: "alerts:review",
  alertsDismiss: "alerts:dismiss",
  alertsFalsePositive: "alerts:dismiss",
  alertsEscalate: "alerts:review",
  alertsConvert: "alerts:convert",
  analysisRead: "analysis:read",
  analysisRun: "analysis:run",
  athletesRead: "athletes:read",
  auditRead: "audit:read",
  evidenceCreate: "evidence:create",
  evidenceModify: "evidence:modify",
  importsRead: "imports:read",
  importsCreate: "imports:create",
  importsCommit: "imports:commit",
  intelligenceRead: "intelligence:read",
  intelligenceCreate: "intelligence:create",
  intelligenceModify: "intelligence:modify",
  investigationsRead: "investigations:read",
  investigationsCreate: "investigations:create",
  investigationsModify: "investigations:modify",
  investigationsAssign: "investigations:assign",
  osintRead: "osint:read",
  osintCollect: "osint:collect",
  osintAdmin: "osint:admin",
  reportsRead: "reports:read",
  reportsGenerate: "reports:generate",
  usersManage: "users:manage",
} as const;

export const DROP_PERMISSIONS = {
  intelligenceRead: "intelligence:read",
  alertsRead: "alerts:read",
  athletesRead: "athletes:read",
  importsRead: "imports:read",
  osintRead: "osint:read",
  investigationsRead: "investigations:read",
  reportsRead: "reports:read",
  auditRead: "audit:read",
  usersManage: "users:manage",
} as const;

export type PermissionKey = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];